# Site settings
title: Zhreshold
#email: cheungchih@gmail.com
url: http://ZhreShold.github.io
baseurl: ""
header-img: img/home-bg.jpg
description: "ZhreShold - Joshua Zhang's personal website."

paginate: 5
paginate_path: "/logs/page:num/"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#f6f6f6'
  primary-font: '#000000'
  links: '#219ab3'

# Footer settings
footer: ZhreShold

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/ZhreShold
  - title: flickr
    url: https://www.flickr.com/photos/zhreshold


# Build settings
markdown: kramdown
permalink: pretty
