# Site settings
title: Zhreshold
#email: cheungchih@gmail.com
url: http://ZhreShold.github.io
baseurl: ""
header-img: img/home-bg.jpg
description: "ZhreShold - Joshua Zhang's personal website."

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/logs/page:num/"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#f6f6f6'
  primary-font: '#000000'
  links: '#219ab3'

# Footer settings
footer: ZhreShold

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ZhreShold
    family: fa
  - title: scholar
    url: https://scholar.google.com/citations?hl=en&user=nZr0oXQAAAAJ
    family: ai
  - title: linkedin
    url: https://www.linkedin.com/in/zhreshold
    family: fa


# Build settings
markdown: kramdown
permalink: pretty
